name = "esgleam"
version = "0.6.0"
gleam = ">= 0.32.0"

description = "esbuild for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "Enderchief", repo = "esgleam" }
# links = [{ title = "Website", href = "https://gleam.run" }]

target = "javascript"

[javascript]
typescript_declarations = true

[dependencies]
gleam_stdlib = "~> 0.34"
simplifile = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
